version: '3.8'
services:
  sqlserver:
    container_name: bookstore-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Dev@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"Your_password123\" -Q \"SELECT 1\""]
      interval: 10s
      timeout: 10s
      retries: 10

  bookstore.api:
    container_name: bookstore-api
    image: ${DOCKER_REGISTRY-}bookstoreapi
    build:
      context: .
      dockerfile: Bookstore.Api/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=127.0.0.1,1433;Database=BookstoreDB;User Id=sa;Password=Dev@123;TrustServerCertificate=True;"
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "5000:80"