services:
  bookstore.api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/bookstore.api.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Dev@123456
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=BookstoreDB;User Id=sa;Password=Dev@123456;TrustServerCertificate=True;
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8081:8081"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bookstore-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dev@123456
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"${SA_PASSWORD}\" -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata:
